### ISSUE TITLE
Imágenes rotas en perfiles

### ISSUE THREAD

**Issue by pipegoods** [pipegoods/tech-global#6]
Hola, hay imágenes rotas en algunos miembros, concretamente en los de **Daniel Medina** y **Gabriel González**, estas imágenes se están bloqueando por CORS, 

Recomendación, subir las imágenes  en un [Cloudinary](https://cloudinary.com/).

![Captura de pantalla 2023-03-06 a la(s) 11 06 26 p m](https://user-images.githubusercontent.com/31173782/223318218-4bcf8e46-ce23-4696-9edc-8063b31aa39a.png)

**Comment by gaabgonca** [comment]
Solved by PR #7
