### ISSUE TITLE
[PROPOSAL] Limit technologies per contributor

### ISSUE THREAD

**Issue by gaabgonca** [pipegoods/tech-global#8]
Currently we have different sizes of technologies sets by contributors. This can lead to an inconsistent UI. 

I suggest limiting the amount of technologies per contributor to 5, so they can showcase the 5 most important according to their profile. 

What do you think @pipegoods ?

**Comment by pipegoods** [comment]
I think it's a good idea, so we can make the content of the cards not bigger than others... for now let's limit ourselves with a slice that only shows the first 5.

**Comment by pipegoods** [comment]
I think it's a good idea, so we can make the content of the cards not bigger than others... for now let's limit ourselves with a slice that only shows the first 5.
